#!/usr/bin/env bash

echo "Setting bspwm values for home_DP1_DP2_eDP1"

# reorder monitors
bspc wm -O eDP1 DP1 DP2

bspc monitor eDP1 -d 1
bspc monitor DP1 -d 2 3 4 5 6 7 8
bspc monitor DP2 -d 9 10
bspc config window_gap 40
