#!/usr/bin/env bash

echo "Reloading bspwmrc..."

wmname compiz

xsetroot -cursor_name left_ptr
setxkbmap -option caps:super

bspc monitor eDP1 -d 1 2
bspc monitor DP2 -d 3 4 5 6 7 8 9 10

#primary=$(xrandr -q | grep primary | cut -d " " -f1)
#bspc monitor $primary -d I II III IV V VI VII VIII

#others=$(xrandr -q | grep " connected" | grep -v primary | cut -d " " -f1)
#for m in $others; do
#  bspc monitor $m -d IX X
#done

bspc config border_width         2
bspc config window_gap          40

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true

bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config focus_follows_pointer true

if pgrep -x "sxhkd" > /dev/null
then
  pkill -USR1 -x sxhkd;
else
  sxhkd &
fi

launch_polybar

echo "bspwmrc reloaded!"
