#! /bin/sh

bspc monitor eDP-1 -d I II III IV V VI
bspc monitor DP-1 -d VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_focus true

# launch polybar

polybar eve > /tmp/polybar_eve.log 2> /tmp/polybar_eve.log </dev/null &
echo "$(date): polybar eve launched from bspwmrc" >> /tmp/polybar_eve.log
