#!/usr/bin/env bash

echo "Setting bspwm values for home_eDP1_left_of_DP1"

# bspc monitor DP2 -r
bspc wm -O eDP1 DP1
bspc monitor eDP1 -d 1 2
bspc monitor DP1 -d 3 4 5 6 7 8 9 10
bspc config window_gap 40
